### ISSUE TITLE
Bearer Token

### ISSUE THREAD

**Issue by matheustgf10** [Brun0Nasc/Frequencias-Backend#1]
Boa noite guys, estou com dúvidas relacionado a como gerar o Bearer Token para consumir as rotas com autenticação.

**Comment by Brun0Nasc** [comment]
Boa noite, desculpe pela demora, pra gerar o Token, tu acessa pela rota de /login, no banco que tá no Elephant as credenciais são admin, tu passa "email":"admin" e "senha": "admin" no Post. Assim tu recebe o token de resposta

**Comment by Brun0Nasc** [comment]
Opa, o erro era outro kkkkkkk, a autenticação tava na rota errada
